### ISSUE TITLE
build fails after updating to 1.6.1 from 1.6.0

### ISSUE THREAD

**Issue by albanyacademy** [frontendr/bemmed#161]
**Describe the bug**
Get "module has no exports" error messages.
```
WARNING in ./yaddayadda/index.js 23:22-25
export 'default' (imported as 'BEM') was not found in 'bemmed' (module has no exports)
```

The only change is updating this one package by itself.

**Comment by frontendr** [comment]
@albanyacademy I've just published [release 1.6.2](https://github.com/frontendr/bemmed/releases/tag/1.6.2) which fixes this issue.
